[package]
authors = ["Luke Chu <lukewchu@outlook.com>"]
edition = "2018"
name = "derivative-calculator"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
